### ISSUE TITLE
How add exemptions for a  namespace

### ISSUE THREAD

**Issue by skyox** [FairwindsOps/polaris#488] opened 2021-02-03 09:14 UTC
How add exemptionfor whole namespace?

```
    exemptions:
      - namespace: kube-system
      - namespace: kube-public 
      - namespace: default
      - namespace: istio-system
      - namespace: kube-node-lease
      -
```

**Comment by rbren** [comment] 2021-02-03 14:46
Is this not working for you? I believe that syntax should be supported.

**Comment by rbren** [comment] 2021-02-03 14:50
Confirmed this is working locally for me

**Comment by rbren** [comment] 2021-02-03 14:53
Looks like it's fixed in master, but not latest - will get a release out shortly

**Comment by dbones** [comment] 2021-02-03 22:40
@skyox, I just updated to 3.1.0 this works for me 

![image](https://user-images.githubusercontent.com/183849/106818844-cad10b80-6670-11eb-8e43-9b9b99d6254f.png)

**Comment by skyox** [comment] 2021-02-04 01:42
thinks, i will try to update 3.1.0

**Comment by skyox** [comment] 2021-02-04 02:35
I just updated to 3.1.0 this works for me too.

**Closed** 2021-02-04 02:34 UTC
